Name:           ros-kinetic-serial
Version:        1.2.1
Release:        1%{?dist}
Summary:        ROS serial package

Group:          Development/Libraries
License:        MIT
URL:            http://wjwwood.github.com/serial/
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  boost-devel
BuildRequires:  ros-kinetic-catkin

%description
Serial is a cross-platform, simple to use library for using serial ports on
computers. This library provides a C++, object oriented interface for
interacting with RS-232 like devices on Linux and Windows.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Sun Apr 24 2016 William Woodall <william@osrfoundation.org> - 1.2.1-1
- Autogenerated by Bloom

* Wed Mar 23 2016 William Woodall <william@osrfoundation.org> - 1.2.1-0
- Autogenerated by Bloom

